---
- hosts: 10.255.0.1
  connection: local
  gather_facts: no

  vars:
    a10_host: "10.255.0.1"
  tasks:
  - name: Import cert file
    a10_import:
      a10_host: "{{ a10_host }}"
      a10_port: "{{ a10_port }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      ssl_cert: "server.crt"
      use_mgmt_port: True
      overwrite: True
      remote_file: "sftp://root@10.255.0.250/root/certs/server.crt"
      password: "a10"
      state: present
      partition: shared

  - name: Import key
    a10_import:
      a10_host: "{{ a10_host }}"
      a10_port: "{{ a10_port }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      ssl_key: "server.key"
      use_mgmt_port: True
      overwrite: True
      remote_file: "sftp://root@10.255.0.250/root/certs/server.key"
      password: "a10"
      state: present
      partition: shared

